import type { EnergyProvider } from "@/lib/database.types";

// Demo data used when Supabase is not configured
export const demoProviders: EnergyProvider[] = [
  {
    id: "1",
    name: "Vattenfall",
    kwh_rate: 0.285,
    gas_rate: 1.25,
    standing_charge_electricity: 7.95,
    standing_charge_gas: 7.95,
    contract_type: "vast",
    contract_duration_months: 12,
    green_energy: true,
    rating: 4.2,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Eneco",
    kwh_rate: 0.272,
    gas_rate: 1.18,
    standing_charge_electricity: 6.95,
    standing_charge_gas: 6.95,
    contract_type: "vast",
    contract_duration_months: 36,
    green_energy: true,
    rating: 4.5,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Essent",
    kwh_rate: 0.295,
    gas_rate: 1.32,
    standing_charge_electricity: 8.5,
    standing_charge_gas: 8.5,
    contract_type: "vast",
    contract_duration_months: 12,
    green_energy: false,
    rating: 3.8,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Budget Energie",
    kwh_rate: 0.258,
    gas_rate: 1.15,
    standing_charge_electricity: 5.5,
    standing_charge_gas: 5.5,
    contract_type: "variabel",
    contract_duration_months: 0,
    green_energy: false,
    rating: 3.5,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Greenchoice",
    kwh_rate: 0.268,
    gas_rate: 1.2,
    standing_charge_electricity: 6.5,
    standing_charge_gas: 6.5,
    contract_type: "vast",
    contract_duration_months: 12,
    green_energy: true,
    rating: 4.3,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "ANWB Energie",
    kwh_rate: 0.275,
    gas_rate: 1.23,
    standing_charge_electricity: 7.0,
    standing_charge_gas: 7.0,
    contract_type: "vast",
    contract_duration_months: 12,
    green_energy: true,
    rating: 4.1,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Vandebron",
    kwh_rate: 0.245,
    gas_rate: 1.08,
    standing_charge_electricity: 6.0,
    standing_charge_gas: 6.0,
    contract_type: "dynamisch",
    contract_duration_months: 0,
    green_energy: true,
    rating: 4.4,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    name: "Tibber",
    kwh_rate: 0.238,
    gas_rate: 1.05,
    standing_charge_electricity: 5.99,
    standing_charge_gas: 5.99,
    contract_type: "dynamisch",
    contract_duration_months: 0,
    green_energy: true,
    rating: 4.6,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "9",
    name: "EasyEnergy",
    kwh_rate: 0.242,
    gas_rate: 1.09,
    standing_charge_electricity: 5.75,
    standing_charge_gas: 5.75,
    contract_type: "dynamisch",
    contract_duration_months: 0,
    green_energy: false,
    rating: 3.9,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Oxxio",
    kwh_rate: 0.289,
    gas_rate: 1.28,
    standing_charge_electricity: 7.5,
    standing_charge_gas: 7.5,
    contract_type: "variabel",
    contract_duration_months: 0,
    green_energy: false,
    rating: 3.6,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "11",
    name: "Mega",
    kwh_rate: 0.265,
    gas_rate: 1.16,
    standing_charge_electricity: 6.25,
    standing_charge_gas: 6.25,
    contract_type: "variabel",
    contract_duration_months: 0,
    green_energy: false,
    rating: 3.7,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "12",
    name: "Pure Energie",
    kwh_rate: 0.255,
    gas_rate: 1.14,
    standing_charge_electricity: 5.95,
    standing_charge_gas: 5.95,
    contract_type: "vast",
    contract_duration_months: 12,
    green_energy: true,
    rating: 4.0,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "13",
    name: "Frank Energie",
    kwh_rate: 0.24,
    gas_rate: 1.06,
    standing_charge_electricity: 5.85,
    standing_charge_gas: 5.85,
    contract_type: "dynamisch",
    contract_duration_months: 0,
    green_energy: true,
    rating: 4.5,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "14",
    name: "Energie Direct",
    kwh_rate: 0.292,
    gas_rate: 1.3,
    standing_charge_electricity: 8.0,
    standing_charge_gas: 8.0,
    contract_type: "variabel",
    contract_duration_months: 0,
    green_energy: false,
    rating: 3.3,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "15",
    name: "Nederlandse Energie Maatschappij",
    kwh_rate: 0.278,
    gas_rate: 1.21,
    standing_charge_electricity: 7.25,
    standing_charge_gas: 7.25,
    contract_type: "vast",
    contract_duration_months: 24,
    green_energy: false,
    rating: 3.4,
    logo_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];
